// All 3D model iframe URLs extracted from the provided data
export const modelUrls = [
  { id: 1, name: "Model 48", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/48", qrCode: "/qrcodes/hat48qr.png" },
  { id: 2, name: "Model 49", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/49", qrCode: "/qrcodes/hat49qr.png" },
  { id: 3, name: "Model 50", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/50", qrCode: "/qrcodes/hat50qr.png" },
  { id: 4, name: "Model 51", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/51", qrCode: "/qrcodes/hat51qr.png" },
  { id: 5, name: "Model 52", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/52", qrCode: "/qrcodes/hat52qr.png" },
  { id: 6, name: "Model 53", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/53", qrCode: "/qrcodes/hat53qr.png" },
  { id: 7, name: "Model 54", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/54", qrCode: "/qrcodes/hat54qr.png" },
  { id: 8, name: "Model 55", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/55", qrCode: "/qrcodes/hat55qr.png" },
  {
    id: 9,
    name: "Bucket Hat in Knit with Strass Cord",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/BUCKET%20HAT%20IN%20KNIT%20WITH%20STRASS%20CORD",
    qrCode: "/qrcodes/hat27qr.png",
  },
  {
    id: 10,
    name: "Coated Gro Indiana Jones Hat with Tassels",
    category: "winter",
    url: "https://famous-sunshine-190da9.netlify.app/COATED%20GRO%20INDIANA%20JONES%20HAT%20WITH%20TASSELS",
    qrCode: "/qrcodes/hat4qr.png",
  },
  {
    id: 11,
    name: "Cowboy Hat with Patch",
    category: "winter",
    url: "https://famous-sunshine-190da9.netlify.app/COWBOY%20HAT%20WITH%20PATCH",
    qrCode: "/qrcodes/hat6qr.png",
  },
  {
    id: 12,
    name: "Crochet Bucket Hat with Cut-Outs",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/CROCHET%20BUCKET%20HAT%20WITH%20CUT-OUTS",
    qrCode: "/qrcodes/hat29qr.png",
  },
  // { id: 13, name: "Crochet Pamela Bag", category: "winter", url: "https://famous-sunshine-190da9.netlify.app/CROCHET%20PAMELA%20BAG" },
  // {
  //   id: 14,
  //   name: "Crochet Pamela Bag with Diamond Pattern",
  //   url: "https://famous-sunshine-190da9.netlify.app/CROCHET%20PAMELA%20BAG%20WITH%20DIAMOND%20PATTERN",
  // },
  {
    id: 15,
    name: "Crochet Pamela Hat with Diamond Pattern",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/CROCHET%20PAMELA%20HAT%20WITH%20DIAMOND%20PATTERN",
    qrCode: "/qrcodes/hat33qr.png",
  },
  {
    id: 16,
    name: "Dyed Denim Flat Cap with Frayed Sides",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/DYED%20DENIM%20FLAT%20CAP%20WITH%20FRAYED%20SIDES",
    qrCode: "/qrcodes/hat8qr.png",
  },
  {
    id: 17,
    name: "Extra-Fine Borsalino Hat",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/EXTRA-FINE%20BORSALINO%20HAT",
    qrCode: "/qrcodes/hat25qr.png",
  },
  {
    id: 18,
    name: "Extra-Fine Malted Rafia Fedora Hat",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/EXTRA-FINE%20MALTED%20RAFIA%20FEDORA%20HAT",
    qrCode: "/qrcodes/hat13qr.png",
  },
  {
    id: 19,
    name: "Fedora Hat with Large Perforated Brim",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/FEDOARA%20HAT%20WITH%20LARGE%20PERFORATED%20BRIM",
    qrCode: "/qrcodes/hat23qr.png",
  },
  {
    id: 20,
    name: "Fedora Hat with Embossing",
    category: "winter",
    url: "https://famous-sunshine-190da9.netlify.app/FEDORA%20HAT%20WITH%20EMBOSSING",
    qrCode: "/qrcodes/hat5qr.png",
  },
  {
    id: 21,
    name: "Fedora Hat with Grosgrain Ribbon and Stitching",
    category: "winter",
    url: "https://famous-sunshine-190da9.netlify.app/FEDORA%20HAT%20WITH%20GROSGRAIN%20RIBBON%20AND%20STITCHING",
    qrCode: "/qrcodes/hat2qr.png",
  },
  {
    id: 22,
    name: "Fedora Hat with Grosgrain Ribbon and Wing Embroidery",
    category: "winter",
    url: "https://famous-sunshine-190da9.netlify.app/FEDORA%20HAT%20WITH%20GROSGRAIN%20RIBBON%20AND%20WING%20EMBROIDERY",
    qrCode: "/qrcodes/hat3qr.png",
  },
  {
    id: 23,
    name: "Fedora Hat with Perforated Crown",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/FEDORA%20HAT%20WITH%20PERFORATED%20CROWN",
    qrCode: "/qrcodes/hat24qr.png",
  },
  {
    id: 24,
    name: "Fine Crochet Indiana Jones Hat",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/FINE%20CROCHET%20INDIANA%20JONES%20HAT",
    qrCode: "/qrcodes/hat26qr.png",
  },
  {
    id: 25,
    name: "Fisherman Style Hat with Denim Chinstrap",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/FISHERMAN%20STYLE%20HAT%20WITH%20DENIM%20CHINSTRAP%20QUILTED%20BRIM%20AND%20DOUBLE%20FRAYING",
    qrCode: "/qrcodes/hat11qr.png",
  },
  {
    id: 26,
    name: "Hat Cut with Visor and Band",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/HAT%20CUT%20WITH%20VISOR%20AND%20BAND",
    qrCode: "/qrcodes/hat28qr.png",
  },
  {
    id: 27,
    name: "Indiana Jones Hat with Grosgrain Ribbon",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/INDIANA%20JONES%20HAT%20WITH%20GROSGRAIN%20RIBBON%20AND%20STITCHING",
    qrCode: "/qrcodes/hat1qr.png",
  },
  {
    id: 28,
    name: "Lapin Felt Borsalino Hat with Mirage Ribbon",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/LAPIN%20FELT%20BORSALINO%20HAT%20WITH%20MIRAGE%20RIBBON",
    qrCode: "/qrcodes/hat7qr.png",
  },
  {
    id: 29,
    name: "Original Panama Borsalino Hat Grade -10",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/ORIGINAL%20PANAMA%20BORSALINO%20HAT%20GRADE%20-%2010",
    qrCode: "/qrcodes/hat15qr.png",
  },
  {
    id: 30,
    name: "Original Panama Borsalino Hat Grade 10",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/ORIGINAL%20PANAMA%20BORSALINO%20HAT%20GRADE%2010",
    qrCode: "/qrcodes/hat21qr.png",
  },
  {
    id: 31,
    name: "Original Panama Borsalino Hat Grade 10 Jhoot",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/ORIGINAL%20PANAMA%20BORSALINO%20HAT%20GRADE%2010jhoot",
    qrCode: "/qrcodes/hat15qr.png",
  },
  { id: 32, name: "Pamela", category: "summer", url: "https://famous-sunshine-190da9.netlify.app/pamela", qrCode: "/qrcodes/hat17qr.png" },
  {
    id: 33,
    name: "Paper Cowboy Hat with Printed Ribbon",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/PAPER%20COWBOY%20HAT%20WITH%20PRINTED%20RIBBON",
    qrCode: "/qrcodes/hat20qr.png",
  },
  { id: 34, name: "Paper Pork Pie Hat", category: "summer", url: "https://famous-sunshine-190da9.netlify.app/PAPER%20PORK%20PIE%20HAT", qrCode: "/qrcodes/hat19qr.png" },
  { id: 35, name: "Raffia - Straw Hat", category: "summer", url: "https://famous-sunshine-190da9.netlify.app/RAFFIA%20-%20STRAW%20HAT", qrCode: "/qrcodes/hat31qr.png" },
  { id: 36, name: "Raffia Straw Hat", category: "summer", url: "https://famous-sunshine-190da9.netlify.app/RAFFIA%20STRAW%20HAT", qrCode: "/qrcodes/hat18qr.png" },
  { id: 37, name: "Rafia Fedora Hat", category: "summer", url: "https://famous-sunshine-190da9.netlify.app/RAFIA%20FEDORA%20HAT" },
  {
    id: 38,
    name: "Six-Panel Baseball Cap with Button",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/SIX-PANEL%20BASEBALL%20CAP%20WITH%20BUTTON",
    qrCode: "/qrcodes/hat10qr.png",
  },
  {
    id: 39,
    name: "Stewart Pattern Hat with Frayed Visor",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/STEWART%20PATTERN%20HAT%20WITH%20FRAYED%20VISOR",
    qrCode: "/qrcodes/hat9qr.png",
  },
  {
    id: 40,
    name: "Stitched Perforated Pamela Hat",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/STITCHED%20PERORATED%20PAMELA%20HAT",
    qrCode: "/qrcodes/hat22qr.png",
  },
  {
    id: 41,
    name: "Striped Crochet Pamela Hat",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/STRIPED%20CROCHET%20PAMELA%20HAT",
    qrCode: "/qrcodes/hat16qr.png",
  },
  {
    id: 42,
    name: "Woven Straw Flat Hat",
    category: "summer",
    url: "https://famous-sunshine-190da9.netlify.app/WOVEN%20STRAW%20FLAT%20HAT",
    qrCode: "/qrcodes/hat30qr.png",
  },
]

export type Model = (typeof modelUrls)[number]
